spring.application.name=tecnoweb-grupo24sa
server.port=${PORT:8080}

# Credenciales de PagoFacil
pagofacil.token.service=uwu
pagofacil.token.secret=uwu
# URL de callback: se lee primero desde variable de entorno PAGOFACIL_CALLBACK_URL
pagofacil.callback.url=https://uwu/grupo24sa/pagofacil/callback
